sudo: required
services:
    - docker

before_install:
    - docker build -t red3nzo/docker-react-ci -f Dockerfile.dev .

script:
    - docker run red3nzo/docker-react-ci npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-668085491851"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secrect_access_key:
        secure: "$AWS_SECRET_KEY"
